// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNLyU4VfjSReObene3kWap369i5D3gIM0',
    appId: '1:220351166102:web:7b4e06f898bffff6a234b7',
    messagingSenderId: '220351166102',
    projectId: 'focus-app-abc37',
    authDomain: 'focus-app-abc37.firebaseapp.com',
    databaseURL: 'https://focus-app-abc37-default-rtdb.firebaseio.com',
    storageBucket: 'focus-app-abc37.firebasestorage.app',
    measurementId: 'G-2RZTHPE69B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZi4NIglnrChq3Vw0ukbC4YdASyucH-PE',
    appId: '1:220351166102:android:99c71ba9a6618b98a234b7',
    messagingSenderId: '220351166102',
    projectId: 'focus-app-abc37',
    databaseURL: 'https://focus-app-abc37-default-rtdb.firebaseio.com',
    storageBucket: 'focus-app-abc37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtZxocb_caplY-phbkiyZjKsfB3yt4Nhc',
    appId: '1:220351166102:ios:265f7e3be93f6a04a234b7',
    messagingSenderId: '220351166102',
    projectId: 'focus-app-abc37',
    databaseURL: 'https://focus-app-abc37-default-rtdb.firebaseio.com',
    storageBucket: 'focus-app-abc37.firebasestorage.app',
    androidClientId:
        '220351166102-bp7fs9eq5avbihhls7b6d93ri37boksc.apps.googleusercontent.com',
    iosClientId:
        '220351166102-aenr90ve8rmv6tt7o80nq7rme34sqmf1.apps.googleusercontent.com',
    iosBundleId: 'com.example.focusApp',
  );
}
